name: Haskell Stack CI

on: [push]

jobs:
  build:
   
    runs-on: fpco/stack-build

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: stack --system-ghc build
    - name: Run tests
      run: stack --system-ghc test
