name: Haskell Stack CI

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: cabal install --only-dependencies --enable-tests    
    - name: Install stack
      if: failure()
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
        stack setup
    - name: Build
      run: |
        cabal configure --enable-tests
        cabal build
    - name: Build with stack
      if: failure()
      run: stack build
    - name: Run tests
      run: cabal test
    - name: Run tests with stack
      if: failure()
      run: stack test
